//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VATSoapService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vat", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VATSoapService.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VATSoapService.ArrayOfString))]
    public partial class vat : object
    {
        
        private VATSoapService.ArrayOfAnyType vNIDField;
        
        private VATSoapService.ArrayOfAnyType vtinField;
        
        private VATSoapService.ArrayOfAnyType vtitleNameField;
        
        private VATSoapService.ArrayOfAnyType vNameField;
        
        private VATSoapService.ArrayOfAnyType vSurnameField;
        
        private VATSoapService.ArrayOfAnyType vBranchTitleNameField;
        
        private VATSoapService.ArrayOfAnyType vBranchNameField;
        
        private VATSoapService.ArrayOfAnyType vBranchNumberField;
        
        private VATSoapService.ArrayOfAnyType vBuildingNameField;
        
        private VATSoapService.ArrayOfAnyType vFloorNumberField;
        
        private VATSoapService.ArrayOfAnyType vVillageNameField;
        
        private VATSoapService.ArrayOfAnyType vRoomNumberField;
        
        private VATSoapService.ArrayOfAnyType vHouseNumberField;
        
        private VATSoapService.ArrayOfAnyType vMooNumberField;
        
        private VATSoapService.ArrayOfAnyType vSoiNameField;
        
        private VATSoapService.ArrayOfAnyType vStreetNameField;
        
        private VATSoapService.ArrayOfAnyType vThambolField;
        
        private VATSoapService.ArrayOfAnyType vAmphurField;
        
        private VATSoapService.ArrayOfAnyType vProvinceField;
        
        private VATSoapService.ArrayOfAnyType vPostCodeField;
        
        private VATSoapService.ArrayOfAnyType vBusinessFirstDateField;
        
        private VATSoapService.ArrayOfAnyType vmsgerrField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VATSoapService.ArrayOfAnyType vNID
        {
            get
            {
                return this.vNIDField;
            }
            set
            {
                this.vNIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VATSoapService.ArrayOfAnyType vtin
        {
            get
            {
                return this.vtinField;
            }
            set
            {
                this.vtinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VATSoapService.ArrayOfAnyType vtitleName
        {
            get
            {
                return this.vtitleNameField;
            }
            set
            {
                this.vtitleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public VATSoapService.ArrayOfAnyType vName
        {
            get
            {
                return this.vNameField;
            }
            set
            {
                this.vNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public VATSoapService.ArrayOfAnyType vSurname
        {
            get
            {
                return this.vSurnameField;
            }
            set
            {
                this.vSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public VATSoapService.ArrayOfAnyType vBranchTitleName
        {
            get
            {
                return this.vBranchTitleNameField;
            }
            set
            {
                this.vBranchTitleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public VATSoapService.ArrayOfAnyType vBranchName
        {
            get
            {
                return this.vBranchNameField;
            }
            set
            {
                this.vBranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public VATSoapService.ArrayOfAnyType vBranchNumber
        {
            get
            {
                return this.vBranchNumberField;
            }
            set
            {
                this.vBranchNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public VATSoapService.ArrayOfAnyType vBuildingName
        {
            get
            {
                return this.vBuildingNameField;
            }
            set
            {
                this.vBuildingNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public VATSoapService.ArrayOfAnyType vFloorNumber
        {
            get
            {
                return this.vFloorNumberField;
            }
            set
            {
                this.vFloorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public VATSoapService.ArrayOfAnyType vVillageName
        {
            get
            {
                return this.vVillageNameField;
            }
            set
            {
                this.vVillageNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public VATSoapService.ArrayOfAnyType vRoomNumber
        {
            get
            {
                return this.vRoomNumberField;
            }
            set
            {
                this.vRoomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public VATSoapService.ArrayOfAnyType vHouseNumber
        {
            get
            {
                return this.vHouseNumberField;
            }
            set
            {
                this.vHouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public VATSoapService.ArrayOfAnyType vMooNumber
        {
            get
            {
                return this.vMooNumberField;
            }
            set
            {
                this.vMooNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public VATSoapService.ArrayOfAnyType vSoiName
        {
            get
            {
                return this.vSoiNameField;
            }
            set
            {
                this.vSoiNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public VATSoapService.ArrayOfAnyType vStreetName
        {
            get
            {
                return this.vStreetNameField;
            }
            set
            {
                this.vStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public VATSoapService.ArrayOfAnyType vThambol
        {
            get
            {
                return this.vThambolField;
            }
            set
            {
                this.vThambolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public VATSoapService.ArrayOfAnyType vAmphur
        {
            get
            {
                return this.vAmphurField;
            }
            set
            {
                this.vAmphurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public VATSoapService.ArrayOfAnyType vProvince
        {
            get
            {
                return this.vProvinceField;
            }
            set
            {
                this.vProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public VATSoapService.ArrayOfAnyType vPostCode
        {
            get
            {
                return this.vPostCodeField;
            }
            set
            {
                this.vPostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public VATSoapService.ArrayOfAnyType vBusinessFirstDate
        {
            get
            {
                return this.vBusinessFirstDateField;
            }
            set
            {
                this.vBusinessFirstDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public VATSoapService.ArrayOfAnyType vmsgerr
        {
            get
            {
                return this.vmsgerrField;
            }
            set
            {
                this.vmsgerrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.Generic.List<object>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ConfigurationName="VATSoapService.vatserviceRD3Soap")]
    public interface vatserviceRD3Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/Service", ReplyAction="*")]
        System.Threading.Tasks.Task<VATSoapService.ServiceResponse> ServiceAsync(VATSoapService.ServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/ServiceArr", ReplyAction="*")]
        System.Threading.Tasks.Task<VATSoapService.ServiceArrResponse> ServiceArrAsync(VATSoapService.ServiceArrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Service", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public VATSoapService.ServiceRequestBody Body;
        
        public ServiceRequest()
        {
        }
        
        public ServiceRequest(VATSoapService.ServiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ProvinceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int BranchNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int AmphurCode;
        
        public ServiceRequestBody()
        {
        }
        
        public ServiceRequestBody(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode)
        {
            this.username = username;
            this.password = password;
            this.TIN = TIN;
            this.Name = Name;
            this.ProvinceCode = ProvinceCode;
            this.BranchNumber = BranchNumber;
            this.AmphurCode = AmphurCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceResponse", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public VATSoapService.ServiceResponseBody Body;
        
        public ServiceResponse()
        {
        }
        
        public ServiceResponse(VATSoapService.ServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VATSoapService.vat ServiceResult;
        
        public ServiceResponseBody()
        {
        }
        
        public ServiceResponseBody(VATSoapService.vat ServiceResult)
        {
            this.ServiceResult = ServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArr", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public VATSoapService.ServiceArrRequestBody Body;
        
        public ServiceArrRequest()
        {
        }
        
        public ServiceArrRequest(VATSoapService.ServiceArrRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceArrRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public VATSoapService.ArrayOfString TINs;
        
        public ServiceArrRequestBody()
        {
        }
        
        public ServiceArrRequestBody(string username, string password, VATSoapService.ArrayOfString TINs)
        {
            this.username = username;
            this.password = password;
            this.TINs = TINs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArrResponse", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public VATSoapService.ServiceArrResponseBody Body;
        
        public ServiceArrResponse()
        {
        }
        
        public ServiceArrResponse(VATSoapService.ServiceArrResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceArrResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VATSoapService.vat ServiceArrResult;
        
        public ServiceArrResponseBody()
        {
        }
        
        public ServiceArrResponseBody(VATSoapService.vat ServiceArrResult)
        {
            this.ServiceArrResult = ServiceArrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface vatserviceRD3SoapChannel : VATSoapService.vatserviceRD3Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class vatserviceRD3SoapClient : System.ServiceModel.ClientBase<VATSoapService.vatserviceRD3Soap>, VATSoapService.vatserviceRD3Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public vatserviceRD3SoapClient() : 
                base(vatserviceRD3SoapClient.GetDefaultBinding(), vatserviceRD3SoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.vatserviceRD3Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatserviceRD3SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(vatserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), vatserviceRD3SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatserviceRD3SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(vatserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatserviceRD3SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(vatserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatserviceRD3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VATSoapService.ServiceResponse> VATSoapService.vatserviceRD3Soap.ServiceAsync(VATSoapService.ServiceRequest request)
        {
            return base.Channel.ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<VATSoapService.ServiceResponse> ServiceAsync(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode)
        {
            VATSoapService.ServiceRequest inValue = new VATSoapService.ServiceRequest();
            inValue.Body = new VATSoapService.ServiceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TIN = TIN;
            inValue.Body.Name = Name;
            inValue.Body.ProvinceCode = ProvinceCode;
            inValue.Body.BranchNumber = BranchNumber;
            inValue.Body.AmphurCode = AmphurCode;
            return ((VATSoapService.vatserviceRD3Soap)(this)).ServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VATSoapService.ServiceArrResponse> VATSoapService.vatserviceRD3Soap.ServiceArrAsync(VATSoapService.ServiceArrRequest request)
        {
            return base.Channel.ServiceArrAsync(request);
        }
        
        public System.Threading.Tasks.Task<VATSoapService.ServiceArrResponse> ServiceArrAsync(string username, string password, VATSoapService.ArrayOfString TINs)
        {
            VATSoapService.ServiceArrRequest inValue = new VATSoapService.ServiceArrRequest();
            inValue.Body = new VATSoapService.ServiceArrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TINs = TINs;
            return ((VATSoapService.vatserviceRD3Soap)(this)).ServiceArrAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.vatserviceRD3Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.vatserviceRD3Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://rdws.rd.go.th/serviceRD3/vatserviceRD3.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return vatserviceRD3SoapClient.GetBindingForEndpoint(EndpointConfiguration.vatserviceRD3Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return vatserviceRD3SoapClient.GetEndpointAddress(EndpointConfiguration.vatserviceRD3Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            vatserviceRD3Soap,
        }
    }
}
