//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEMSoapService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gems", Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GEMSoapService.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GEMSoapService.ArrayOfString))]
    public partial class gems : object
    {
        
        private GEMSoapService.ArrayOfAnyType vNIDField;
        
        private GEMSoapService.ArrayOfAnyType vTINField;
        
        private GEMSoapService.ArrayOfAnyType vProvinceField;
        
        private GEMSoapService.ArrayOfAnyType vTitleNameField;
        
        private GEMSoapService.ArrayOfAnyType vVATTaxPayerNameField;
        
        private GEMSoapService.ArrayOfAnyType vVATTaxPayerSurnameField;
        
        private GEMSoapService.ArrayOfAnyType vBuildingNumberField;
        
        private GEMSoapService.ArrayOfAnyType vRoomNumberField;
        
        private GEMSoapService.ArrayOfAnyType vFloorNumberField;
        
        private GEMSoapService.ArrayOfAnyType vVillageNameField;
        
        private GEMSoapService.ArrayOfAnyType vHouseNumberField;
        
        private GEMSoapService.ArrayOfAnyType vMooNumberField;
        
        private GEMSoapService.ArrayOfAnyType vSoiNameField;
        
        private GEMSoapService.ArrayOfAnyType vStreetNameField;
        
        private GEMSoapService.ArrayOfAnyType vThambolNameField;
        
        private GEMSoapService.ArrayOfAnyType vAmphurNameField;
        
        private GEMSoapService.ArrayOfAnyType vProvinceNameField;
        
        private GEMSoapService.ArrayOfAnyType vPostCodeField;
        
        private GEMSoapService.ArrayOfAnyType vGuildNameField;
        
        private GEMSoapService.ArrayOfAnyType vPrivilegeDateField;
        
        private GEMSoapService.ArrayOfAnyType vMessErrField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GEMSoapService.ArrayOfAnyType vNID
        {
            get
            {
                return this.vNIDField;
            }
            set
            {
                this.vNIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public GEMSoapService.ArrayOfAnyType vTIN
        {
            get
            {
                return this.vTINField;
            }
            set
            {
                this.vTINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GEMSoapService.ArrayOfAnyType vProvince
        {
            get
            {
                return this.vProvinceField;
            }
            set
            {
                this.vProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public GEMSoapService.ArrayOfAnyType vTitleName
        {
            get
            {
                return this.vTitleNameField;
            }
            set
            {
                this.vTitleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public GEMSoapService.ArrayOfAnyType vVATTaxPayerName
        {
            get
            {
                return this.vVATTaxPayerNameField;
            }
            set
            {
                this.vVATTaxPayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public GEMSoapService.ArrayOfAnyType vVATTaxPayerSurname
        {
            get
            {
                return this.vVATTaxPayerSurnameField;
            }
            set
            {
                this.vVATTaxPayerSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public GEMSoapService.ArrayOfAnyType vBuildingNumber
        {
            get
            {
                return this.vBuildingNumberField;
            }
            set
            {
                this.vBuildingNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public GEMSoapService.ArrayOfAnyType vRoomNumber
        {
            get
            {
                return this.vRoomNumberField;
            }
            set
            {
                this.vRoomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public GEMSoapService.ArrayOfAnyType vFloorNumber
        {
            get
            {
                return this.vFloorNumberField;
            }
            set
            {
                this.vFloorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public GEMSoapService.ArrayOfAnyType vVillageName
        {
            get
            {
                return this.vVillageNameField;
            }
            set
            {
                this.vVillageNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public GEMSoapService.ArrayOfAnyType vHouseNumber
        {
            get
            {
                return this.vHouseNumberField;
            }
            set
            {
                this.vHouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public GEMSoapService.ArrayOfAnyType vMooNumber
        {
            get
            {
                return this.vMooNumberField;
            }
            set
            {
                this.vMooNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public GEMSoapService.ArrayOfAnyType vSoiName
        {
            get
            {
                return this.vSoiNameField;
            }
            set
            {
                this.vSoiNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public GEMSoapService.ArrayOfAnyType vStreetName
        {
            get
            {
                return this.vStreetNameField;
            }
            set
            {
                this.vStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public GEMSoapService.ArrayOfAnyType vThambolName
        {
            get
            {
                return this.vThambolNameField;
            }
            set
            {
                this.vThambolNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public GEMSoapService.ArrayOfAnyType vAmphurName
        {
            get
            {
                return this.vAmphurNameField;
            }
            set
            {
                this.vAmphurNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public GEMSoapService.ArrayOfAnyType vProvinceName
        {
            get
            {
                return this.vProvinceNameField;
            }
            set
            {
                this.vProvinceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public GEMSoapService.ArrayOfAnyType vPostCode
        {
            get
            {
                return this.vPostCodeField;
            }
            set
            {
                this.vPostCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public GEMSoapService.ArrayOfAnyType vGuildName
        {
            get
            {
                return this.vGuildNameField;
            }
            set
            {
                this.vGuildNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public GEMSoapService.ArrayOfAnyType vPrivilegeDate
        {
            get
            {
                return this.vPrivilegeDateField;
            }
            set
            {
                this.vPrivilegeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public GEMSoapService.ArrayOfAnyType vMessErr
        {
            get
            {
                return this.vMessErrField;
            }
            set
            {
                this.vMessErrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.Generic.List<object>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3", ConfigurationName="GEMSoapService.gemserviceRD3Soap")]
    public interface gemserviceRD3Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/gemserviceRD3/Service", ReplyAction="*")]
        System.Threading.Tasks.Task<GEMSoapService.ServiceResponse> ServiceAsync(GEMSoapService.ServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/gemserviceRD3/ServiceArr", ReplyAction="*")]
        System.Threading.Tasks.Task<GEMSoapService.ServiceArrResponse> ServiceArrAsync(GEMSoapService.ServiceArrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Service", Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3", Order=0)]
        public GEMSoapService.ServiceRequestBody Body;
        
        public ServiceRequest()
        {
        }
        
        public ServiceRequest(GEMSoapService.ServiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3")]
    public partial class ServiceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VATTaxPayerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string GuildName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ProvinceCode;
        
        public ServiceRequestBody()
        {
        }
        
        public ServiceRequestBody(string username, string password, string TIN, string VATTaxPayerName, string GuildName, int ProvinceCode)
        {
            this.username = username;
            this.password = password;
            this.TIN = TIN;
            this.VATTaxPayerName = VATTaxPayerName;
            this.GuildName = GuildName;
            this.ProvinceCode = ProvinceCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceResponse", Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3", Order=0)]
        public GEMSoapService.ServiceResponseBody Body;
        
        public ServiceResponse()
        {
        }
        
        public ServiceResponse(GEMSoapService.ServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3")]
    public partial class ServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GEMSoapService.gems ServiceResult;
        
        public ServiceResponseBody()
        {
        }
        
        public ServiceResponseBody(GEMSoapService.gems ServiceResult)
        {
            this.ServiceResult = ServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArr", Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3", Order=0)]
        public GEMSoapService.ServiceArrRequestBody Body;
        
        public ServiceArrRequest()
        {
        }
        
        public ServiceArrRequest(GEMSoapService.ServiceArrRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3")]
    public partial class ServiceArrRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GEMSoapService.ArrayOfString TINs;
        
        public ServiceArrRequestBody()
        {
        }
        
        public ServiceArrRequestBody(string username, string password, GEMSoapService.ArrayOfString TINs)
        {
            this.username = username;
            this.password = password;
            this.TINs = TINs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArrResponse", Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3", Order=0)]
        public GEMSoapService.ServiceArrResponseBody Body;
        
        public ServiceArrResponse()
        {
        }
        
        public ServiceArrResponse(GEMSoapService.ServiceArrResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/gemserviceRD3")]
    public partial class ServiceArrResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GEMSoapService.gems ServiceArrResult;
        
        public ServiceArrResponseBody()
        {
        }
        
        public ServiceArrResponseBody(GEMSoapService.gems ServiceArrResult)
        {
            this.ServiceArrResult = ServiceArrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface gemserviceRD3SoapChannel : GEMSoapService.gemserviceRD3Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class gemserviceRD3SoapClient : System.ServiceModel.ClientBase<GEMSoapService.gemserviceRD3Soap>, GEMSoapService.gemserviceRD3Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public gemserviceRD3SoapClient() : 
                base(gemserviceRD3SoapClient.GetDefaultBinding(), gemserviceRD3SoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.gemserviceRD3Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public gemserviceRD3SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(gemserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), gemserviceRD3SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public gemserviceRD3SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(gemserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public gemserviceRD3SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(gemserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public gemserviceRD3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GEMSoapService.ServiceResponse> GEMSoapService.gemserviceRD3Soap.ServiceAsync(GEMSoapService.ServiceRequest request)
        {
            return base.Channel.ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<GEMSoapService.ServiceResponse> ServiceAsync(string username, string password, string TIN, string VATTaxPayerName, string GuildName, int ProvinceCode)
        {
            GEMSoapService.ServiceRequest inValue = new GEMSoapService.ServiceRequest();
            inValue.Body = new GEMSoapService.ServiceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TIN = TIN;
            inValue.Body.VATTaxPayerName = VATTaxPayerName;
            inValue.Body.GuildName = GuildName;
            inValue.Body.ProvinceCode = ProvinceCode;
            return ((GEMSoapService.gemserviceRD3Soap)(this)).ServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GEMSoapService.ServiceArrResponse> GEMSoapService.gemserviceRD3Soap.ServiceArrAsync(GEMSoapService.ServiceArrRequest request)
        {
            return base.Channel.ServiceArrAsync(request);
        }
        
        public System.Threading.Tasks.Task<GEMSoapService.ServiceArrResponse> ServiceArrAsync(string username, string password, GEMSoapService.ArrayOfString TINs)
        {
            GEMSoapService.ServiceArrRequest inValue = new GEMSoapService.ServiceArrRequest();
            inValue.Body = new GEMSoapService.ServiceArrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TINs = TINs;
            return ((GEMSoapService.gemserviceRD3Soap)(this)).ServiceArrAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.gemserviceRD3Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.gemserviceRD3Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://rdws.rd.go.th/serviceRD3/gemserviceRD3.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return gemserviceRD3SoapClient.GetBindingForEndpoint(EndpointConfiguration.gemserviceRD3Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return gemserviceRD3SoapClient.GetEndpointAddress(EndpointConfiguration.gemserviceRD3Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            gemserviceRD3Soap,
        }
    }
}
