//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TINSoapService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice", ConfigurationName="TINSoapService.checktinpinserviceSoap")]
    public interface checktinpinserviceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/JserviceRD3/checktinpinservice/ServiceTIN", ReplyAction="*")]
        System.Threading.Tasks.Task<TINSoapService.ServiceTINResponse> ServiceTINAsync(TINSoapService.ServiceTINRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/JserviceRD3/checktinpinservice/ServiceTINArr", ReplyAction="*")]
        System.Threading.Tasks.Task<TINSoapService.ServiceTINArrResponse> ServiceTINArrAsync(TINSoapService.ServiceTINArrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceTINRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceTIN", Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice", Order=0)]
        public TINSoapService.ServiceTINRequestBody Body;
        
        public ServiceTINRequest()
        {
        }
        
        public ServiceTINRequest(TINSoapService.ServiceTINRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice")]
    public partial class ServiceTINRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TIN;
        
        public ServiceTINRequestBody()
        {
        }
        
        public ServiceTINRequestBody(string username, string password, string TIN)
        {
            this.username = username;
            this.password = password;
            this.TIN = TIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceTINResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceTINResponse", Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice", Order=0)]
        public TINSoapService.ServiceTINResponseBody Body;
        
        public ServiceTINResponse()
        {
        }
        
        public ServiceTINResponse(TINSoapService.ServiceTINResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice")]
    public partial class ServiceTINResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object ServiceTINResult;
        
        public ServiceTINResponseBody()
        {
        }
        
        public ServiceTINResponseBody(object ServiceTINResult)
        {
            this.ServiceTINResult = ServiceTINResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceTINArrRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceTINArr", Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice", Order=0)]
        public TINSoapService.ServiceTINArrRequestBody Body;
        
        public ServiceTINArrRequest()
        {
        }
        
        public ServiceTINArrRequest(TINSoapService.ServiceTINArrRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice")]
    public partial class ServiceTINArrRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TINSoapService.ArrayOfString TINs;
        
        public ServiceTINArrRequestBody()
        {
        }
        
        public ServiceTINArrRequestBody(string username, string password, TINSoapService.ArrayOfString TINs)
        {
            this.username = username;
            this.password = password;
            this.TINs = TINs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceTINArrResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceTINArrResponse", Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice", Order=0)]
        public TINSoapService.ServiceTINArrResponseBody Body;
        
        public ServiceTINArrResponse()
        {
        }
        
        public ServiceTINArrResponse(TINSoapService.ServiceTINArrResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/JserviceRD3/checktinpinservice")]
    public partial class ServiceTINArrResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object ServiceTINArrResult;
        
        public ServiceTINArrResponseBody()
        {
        }
        
        public ServiceTINArrResponseBody(object ServiceTINArrResult)
        {
            this.ServiceTINArrResult = ServiceTINArrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface checktinpinserviceSoapChannel : TINSoapService.checktinpinserviceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class checktinpinserviceSoapClient : System.ServiceModel.ClientBase<TINSoapService.checktinpinserviceSoap>, TINSoapService.checktinpinserviceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public checktinpinserviceSoapClient() : 
                base(checktinpinserviceSoapClient.GetDefaultBinding(), checktinpinserviceSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.checktinpinserviceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checktinpinserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(checktinpinserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), checktinpinserviceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checktinpinserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(checktinpinserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checktinpinserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(checktinpinserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public checktinpinserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TINSoapService.ServiceTINResponse> TINSoapService.checktinpinserviceSoap.ServiceTINAsync(TINSoapService.ServiceTINRequest request)
        {
            return base.Channel.ServiceTINAsync(request);
        }
        
        public System.Threading.Tasks.Task<TINSoapService.ServiceTINResponse> ServiceTINAsync(string username, string password, string TIN)
        {
            TINSoapService.ServiceTINRequest inValue = new TINSoapService.ServiceTINRequest();
            inValue.Body = new TINSoapService.ServiceTINRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TIN = TIN;
            return ((TINSoapService.checktinpinserviceSoap)(this)).ServiceTINAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TINSoapService.ServiceTINArrResponse> TINSoapService.checktinpinserviceSoap.ServiceTINArrAsync(TINSoapService.ServiceTINArrRequest request)
        {
            return base.Channel.ServiceTINArrAsync(request);
        }
        
        public System.Threading.Tasks.Task<TINSoapService.ServiceTINArrResponse> ServiceTINArrAsync(string username, string password, TINSoapService.ArrayOfString TINs)
        {
            TINSoapService.ServiceTINArrRequest inValue = new TINSoapService.ServiceTINArrRequest();
            inValue.Body = new TINSoapService.ServiceTINArrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TINs = TINs;
            return ((TINSoapService.checktinpinserviceSoap)(this)).ServiceTINArrAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.checktinpinserviceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.checktinpinserviceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://rdws.rd.go.th/jsonRD/checktinpinservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return checktinpinserviceSoapClient.GetBindingForEndpoint(EndpointConfiguration.checktinpinserviceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return checktinpinserviceSoapClient.GetEndpointAddress(EndpointConfiguration.checktinpinserviceSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            checktinpinserviceSoap,
        }
    }
}
