//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonSoapService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="common", Namespace="https://rdws.rd.go.th/serviceRD3/commonserviceRD3")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CommonSoapService.ArrayOfAnyType))]
    public partial class common : object
    {
        
        private CommonSoapService.ArrayOfAnyType vAmphurCodeField;
        
        private CommonSoapService.ArrayOfAnyType vProvinceCodeField;
        
        private CommonSoapService.ArrayOfAnyType vDescriptionField;
        
        private CommonSoapService.ArrayOfAnyType vBusinessTypeCodeField;
        
        private CommonSoapService.ArrayOfAnyType vBusinessTypeNameField;
        
        private CommonSoapService.ArrayOfAnyType vMessErrField;
        
        private CommonSoapService.ArrayOfAnyType vStreetCodeField;
        
        private CommonSoapService.ArrayOfAnyType vStreetNameField;
        
        private CommonSoapService.ArrayOfAnyType vVRTProvinceCodeField;
        
        private CommonSoapService.ArrayOfAnyType vVRTProvinceNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CommonSoapService.ArrayOfAnyType vAmphurCode
        {
            get
            {
                return this.vAmphurCodeField;
            }
            set
            {
                this.vAmphurCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public CommonSoapService.ArrayOfAnyType vProvinceCode
        {
            get
            {
                return this.vProvinceCodeField;
            }
            set
            {
                this.vProvinceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CommonSoapService.ArrayOfAnyType vDescription
        {
            get
            {
                return this.vDescriptionField;
            }
            set
            {
                this.vDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CommonSoapService.ArrayOfAnyType vBusinessTypeCode
        {
            get
            {
                return this.vBusinessTypeCodeField;
            }
            set
            {
                this.vBusinessTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CommonSoapService.ArrayOfAnyType vBusinessTypeName
        {
            get
            {
                return this.vBusinessTypeNameField;
            }
            set
            {
                this.vBusinessTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public CommonSoapService.ArrayOfAnyType vMessErr
        {
            get
            {
                return this.vMessErrField;
            }
            set
            {
                this.vMessErrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public CommonSoapService.ArrayOfAnyType vStreetCode
        {
            get
            {
                return this.vStreetCodeField;
            }
            set
            {
                this.vStreetCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public CommonSoapService.ArrayOfAnyType vStreetName
        {
            get
            {
                return this.vStreetNameField;
            }
            set
            {
                this.vStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public CommonSoapService.ArrayOfAnyType vVRTProvinceCode
        {
            get
            {
                return this.vVRTProvinceCodeField;
            }
            set
            {
                this.vVRTProvinceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public CommonSoapService.ArrayOfAnyType vVRTProvinceName
        {
            get
            {
                return this.vVRTProvinceNameField;
            }
            set
            {
                this.vVRTProvinceNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="https://rdws.rd.go.th/serviceRD3/commonserviceRD3", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.Generic.List<object>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/commonserviceRD3", ConfigurationName="CommonSoapService.commonserviceRD3Soap")]
    public interface commonserviceRD3Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/commonserviceRD3/Service", ReplyAction="*")]
        System.Threading.Tasks.Task<CommonSoapService.ServiceResponse> ServiceAsync(CommonSoapService.ServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Service", Namespace="https://rdws.rd.go.th/serviceRD3/commonserviceRD3", Order=0)]
        public CommonSoapService.ServiceRequestBody Body;
        
        public ServiceRequest()
        {
        }
        
        public ServiceRequest(CommonSoapService.ServiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/commonserviceRD3")]
    public partial class ServiceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string typeofservice;
        
        public ServiceRequestBody()
        {
        }
        
        public ServiceRequestBody(string username, string password, string typeofservice)
        {
            this.username = username;
            this.password = password;
            this.typeofservice = typeofservice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceResponse", Namespace="https://rdws.rd.go.th/serviceRD3/commonserviceRD3", Order=0)]
        public CommonSoapService.ServiceResponseBody Body;
        
        public ServiceResponse()
        {
        }
        
        public ServiceResponse(CommonSoapService.ServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/commonserviceRD3")]
    public partial class ServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CommonSoapService.common ServiceResult;
        
        public ServiceResponseBody()
        {
        }
        
        public ServiceResponseBody(CommonSoapService.common ServiceResult)
        {
            this.ServiceResult = ServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface commonserviceRD3SoapChannel : CommonSoapService.commonserviceRD3Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class commonserviceRD3SoapClient : System.ServiceModel.ClientBase<CommonSoapService.commonserviceRD3Soap>, CommonSoapService.commonserviceRD3Soap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public commonserviceRD3SoapClient() : 
                base(commonserviceRD3SoapClient.GetDefaultBinding(), commonserviceRD3SoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.commonserviceRD3Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public commonserviceRD3SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(commonserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), commonserviceRD3SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public commonserviceRD3SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(commonserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public commonserviceRD3SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(commonserviceRD3SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public commonserviceRD3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CommonSoapService.ServiceResponse> CommonSoapService.commonserviceRD3Soap.ServiceAsync(CommonSoapService.ServiceRequest request)
        {
            return base.Channel.ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CommonSoapService.ServiceResponse> ServiceAsync(string username, string password, string typeofservice)
        {
            CommonSoapService.ServiceRequest inValue = new CommonSoapService.ServiceRequest();
            inValue.Body = new CommonSoapService.ServiceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.typeofservice = typeofservice;
            return ((CommonSoapService.commonserviceRD3Soap)(this)).ServiceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.commonserviceRD3Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.commonserviceRD3Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://rdws.rd.go.th/serviceRD3/commonserviceRD3.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return commonserviceRD3SoapClient.GetBindingForEndpoint(EndpointConfiguration.commonserviceRD3Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return commonserviceRD3SoapClient.GetEndpointAddress(EndpointConfiguration.commonserviceRD3Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            commonserviceRD3Soap,
        }
    }
}
